### ISSUE TITLE
Package checks based on lintr, not goodpractice?

### ISSUE THREAD

**Issue by noamross** [ropensci-org/rodev#36]
**lintr** has had more frequent updates than **goodpractice**, and many of the standalone checks in **goodpractice** have been absorbed into **lintr** now (cyclomatic complexity, etc).  I think it is also easier to define custom linters rather than custom goodpractice checks.  I think a custom RO checking function may be best based on **rcmdcheck**, **covr**, and **lintr** without the addition of **goodpractice**.

**Comment by maelle** [comment]
now there's pkgcheck :-)
