### ISSUE TITLE
CRAN does not like add_ro_desc() text

### ISSUE THREAD

**Issue by cboettig** [ropensci-org/rodev#39]
```r
  new_description <- glue::glue("{description}\n   This package has been peer-reviewed by rOpenSci (v. {version}).")
```

Not sure what the experience of other users has been, but my last CRAN submission objected to this text. (Quote: "What is rOpenSci?").  I think CRAN would be okay with it if we included a link, but actually in my personal opinion I find this a bit weird to include as part of the package description anyway -- if only because I'm pretty sure almost no existing rOpenSci packages state this(?) and it starts sending a confusing message (are those ones not peer reviewed?)  So I think we should remove the suggestion as well from `dev_guide` template.  

I think the readme "badges" are a much better way to convey this information.  If we are claiming that the review was "by rOpenSci", maybe it would make more sense to assert that with the appropriate role code in the `Authors@R` section of DESCRIPTION as well?  Would love to hear thoughts on this!  cc @sckott @karthik @maelle @noamross & co

**Comment by sckott** [comment]
seems good to remove it. folks often list the reviewers as `rev` anyway, so makes it into the description at least sometimes

**Comment by maelle** [comment]
Oops I should have CRAN tested this first 😱

Original  thread https://github.com/ropensci/software-review-meta/issues/62

**Comment by noamross** [comment]
I had forgotten that we did this.  Agreed, it's not necessary. The `rev` Authors are plenty from my perspective.

**Comment by noamross** [comment]
Though should our recommended text under `person()`  be something like, "reviewed _v. X.X.XX_ for rOpenSci"?

**Comment by maelle** [comment]
Dev dev guide corrected, but I'll keep this issue open to keep track of the PRs above. Thanks again @cboettig for the experience report!
