### ISSUE TITLE
helper to replace all old links

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rodev#4]
The helper could be based on using:

* the package name

* the GitHub URL from DESCRIPTION

based on that, it'd look for all occurrences of the current owner of the repository, and produce a list of markers so that it'd be easy to replace all these occurrences (by hand). A bit like what searching in files in RStudio would do, with a bit less input needed.

**Comment by maelle** [comment]
https://github.com/ropensci/webservices/blob/master/checkurls.R

**Comment by sckott** [comment]
i checked with my setup, and you can indeed run lintr or goodpractice, then check the lintr output `x$lintr` like 

```r
> x$lintr
R/rl_citation.R:10:1: style: lines should not be more than 80 characters.
  sprintf('IUCN 2015. IUCN Red List of Threatened Species. Version %s <www.iucnredlist.org>',
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests/test-all.R:1:1: warning: Avoid library() and require() calls in packages
library("testthat")
^~~~~~~
tests/testthat/helper-rredlist.R:2:1: warning: Avoid library() and require() calls in packages
library("vcr")
^~~~~~~
```

and then I can hold command and click on one of the file paths above. Where it opens requires another step though. for iterm shell, this page https://coderwall.com/p/b7e82q/quickly-open-files-in-iterm-with-cmd-click shows you can go to settings and set the default text editor where the file opens, for me that is `sublime text 3`. 

any more details i should give?

**Comment by maelle** [comment]
Thanks a lot! No that's fine!
